Updated repo name

diff --git a/.github/workflows/pypi-release.yml b/.github/workflows/pypi-release.yml
--- a/.github/workflows/pypi-release.yml
+++ b/.github/workflows/pypi-release.yml
@@ -51,7 +51,7 @@ jobs:
     runs-on: ubuntu-latest
     environment:
       name: release
-      url: https://test.pypi.org/project/axiom
+      url: https://test.pypi.org/project/acs-axiom
     permissions:
       id-token: write
     
@@ -86,3 +86,43 @@ jobs:
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
           repository-url: https://test.pypi.org/legacy/
+
+  publish_pypi_prod:
+      
+      needs: publish_pypi_test
+      runs-on: ubuntu-latest
+      environment:
+        name: release
+        url: https://pypi.org/project/acs-axiom
+      permissions:
+        id-token: write
+      
+      steps:
+      
+        - name: Install Python
+          uses: actions/setup-python@v4
+          with:
+            python-version: "3.11"
+
+        - name: Download artifact
+          uses: actions/download-artifact@v3
+          with:
+            name: releases
+            path: dist
+        
+        - name: Install PyPi dependencies
+          run: |
+            python -m pip install --upgrade pip
+            python -m pip install build twine
+
+        - name: Check build artifacts
+          run: |
+            python -m twine check dist/*
+            pwd
+            if [ -f dist/acs-axiom-0.0.0.tar.gz ]; then
+              echo "INVALID VERSION NUMBER"
+              exit 1
+            fi
+
+        - name: Publish package distributions to TestPyPI
+          uses: pypa/gh-action-pypi-publish@release/v1
